import WorkerPlugin from 'worker-plugin'
import { defineNuxtConfig } from '@nuxt/bridge'

export default defineNuxtConfig({
    buildDir: '_nuxt',
    srcDir: 'client/',
    bridge: {
        nitro: false,
        // Auto import composables
        autoImports: true,
    },
    // Auto import components (https://go.nuxtjs.dev/config-components)
    components: true,
    ssr: process.env.SSR === 'true',
    dev: process.env.NODE_ENV !== 'production',
    alias: {
        tslib: 'tslib/tslib.es6.js',
        fflate: 'fflate/esm/browser.js',
    },
    generate: {
        dir: 'public/dist',
    },
    content: {
        dir: 'docs',
        // since the MarkDown files will be generated by docgen cli
        // editing them will be overwritten as soon as the next generation
        // liveEdit: false,
    },
    // Global page headers (https://go.nuxtjs.dev/config-head)
    typescript: {
        strict: true,
        tsConfig: {
            compilerOptions: {
                lib: ['ESNext', 'ESNext.AsyncIterable', 'DOM'],
                types: ['@nuxt/content', '@pinia/nuxt', '@types/node', '@nuxt/types'],
            },
        },
    },
    publicRuntimeConfig: {
        nuxtURL: process.env.NUXT_URL,
        laravelEndpoint: process.env.LARAVEL_URL,
    },
    privateRuntimeConfig: {},
    // Global CSS (https://go.nuxtjs.dev/config-css)
    // '~/assets/css/docs.css'
    css: ['~/assets/css/main.css'],
    loading: {
        continuous: true,
        color: '#37474F',
        height: '3px',
    },
    loadingIndicator: {
        name: 'folding-cube',
        color: 'white',
        background: '#f68723',
    },

    // Plugins to run before rendering page (https://go.nuxtjs.dev/config-plugins)
    plugins: [],

    // Modules for dev and build (recommended) (https://go.nuxtjs.dev/config-modules)
    buildModules: ['nuxt-compress'],
    // Modules (https://go.nuxtjs.dev/config-modules)
    modules: ['@nuxt/content', '@nuxtjs/vuetify'],

    // Vuetify module configuration (https://go.nuxtjs.dev/config-vuetify)
    vuetify: {
        optionsPath: '~/vuetify.options.js',
        defaultAssets: false,
        treeShake: true,
    },

    // Build Configuration (https://go.nuxtjs.dev/config-build)
    build: {
        analyze: process.env.ANALYZE === 'true',
        hardSource: process.env.NODE_ENV === 'development' && process.env.HARD_SOURCE === 'true',
        publicPath: '/resources/',
        extend(config: any, { isClient }: { isClient: boolean }) {
            if (isClient) {
                config.node = {
                    fs: 'empty',
                }
            }

            config.module.rules.push({
                test: /\.mjs$/,
                include: /node_modules/,
                type: 'javascript/auto',
            })

            config.module.rules.push({
                resourceQuery: /blockType=docs/,
                loader: require.resolve('./docgen/empty-object-loader'),
            })

            // config.resolve.alias.vue$ = 'vue/dist/vue.esm.js'
        },
        // @ts-ignore
        extractCSS:
            process.env.NODE_ENV === 'production'
                ? {
                      ignoreOrder: true,
                  }
                : false,
        optimizeCSS: process.env.NODE_ENV === 'production',
    },
})
